### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by BreadGhoti** [preciousimo/musik#1]
is it ok if i use this in a project im working on i will edit the code to my liking. if you want i can give you full credit. i notice that you haven't worked on this in a while  if you want i can give you full credit. thank you

**Comment by preciousimo** [comment]
Thank you for bringing this to my attention, and I appreciate your interest in this project. Feel free to use and modify the code to fit your needs. If you'd like to credit, that would be greatly appreciated, but it's not necessary.

If you have any further questions or need assistance with anything else, please don't hesitate to ask.

**Comment by BreadGhoti** [comment]
tysm
